workflows:
  default-workflow:
    name: Build & Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_WEB_AUTO_DETECT: true
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    scripts:
      # Install dependencies
      - name: Install dependencies
        script: flutter pub get

      - name: Build Flutter web
        script: |
          flutter build web --release
#           Alternative renderers:
#           flutter build web --release --web-renderer canvaskit
#           flutter build web --release --web-renderer auto

    artifacts:
      # Specify the artifact paths for APK and IPA
      - build/web/**
#      - name: web_build
#          path: build/web

    publishing:
      email:
        recipients:
          - harsh.panchal@kodytechnolab.com
        notify:
          success: true
          failure: true